version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./models:/models
      - ollama_data:/root/.ollama
    restart: unless-stopped
  
  vector-db:
    image: weaviate/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
  
  api:
    build: ./interfaces/api
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      - vector-db
    environment:
      OLLAMA_HOST: ollama
      VECTOR_DB_HOST: vector-db
    restart: unless-stopped

volumes:
  ollama_data:
  weaviate_data: